### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Ark1645** [markolalovic/tda-digits#1]
The file named y_1000.npy is missing in the data sub folder

**Comment by markolalovic** [comment]
Hi, I have added the `y_1000.npy` file to the data directory. For a larger sample size, you can run the `prepare_data.py` script located in the scripts directory. This script downloads 10,000 images of digits and saves them as numpy arrays (`X_10000.npy` and `y_10000.npy`) in the data directory. For more details, please refer to the How-to section in the README.

**Comment by Ark1645** [comment]
Thank you
